### ISSUE TITLE
Regarding /supported-open-source/barman/single-server-streaming/step02-backup-setup.mdx

### ISSUE THREAD

**Issue by vrms** [EnterpriseDB/docs#2092] opened 2021-12-02 14:05 UTC
## Summary

the setup fails on the demo

## Where did you see the problem?
https://www.enterprisedb.com/docs/supported-open-source/barman/single-server-streaming/step02-backup-setup/#verifying-the-configuration

## Details

`barman cron` only returns `Starting WAL archiving for server pg` subsequently the rest of the demo fails as well and `barman check pg` never succeeds

```
barman@backup:~$ barman check pg
Server pg:
        WAL archive: FAILED (please make sure WAL shipping is setup)
        PostgreSQL: FAILED
        directories: OK
        retention policy settings: OK
        backup maximum age: OK (no last_backup_maximum_age provided)
        backup minimum size: OK (0 B)
        wal maximum age: OK (no last_wal_maximum_age provided)
        wal size: OK (0 B)
        compression settings: OK
        failed backups: OK (there are 0 failed backups)
        minimum redundancy requirements: OK (have 0 backups, expected at least 0)
        pg_basebackup: OK
        pg_basebackup compatible: FAILED (PostgreSQL version: None, pg_basebackup version: 14.1)
        systemid coherence: OK (no system Id available)
        pg_receivexlog: OK
        pg_receivexlog compatible: FAILED (PostgreSQL version: None, pg_receivexlog version: 14.1)
        receive-wal running: OK
        archiver errors: OK
```

## Expected behavior

`barman check` returns a clean result
## Browser / Platform
W7 Enterprise, Firefox 91.3.0esr (32-Bit)

**Comment by josh-heyer** [comment] 2022-02-07 21:30
Duplicate of 2224

**Closed by josh-heyer** 2022-02-07 21:30 UTC
