### ISSUE TITLE
Problem on dblink_ora topic (and others) for v12

### ISSUE THREAD

**Issue by jericson-edb** [EnterpriseDB/docs#1365] opened 2021-05-12 16:16 UTC
## Summary
Many pages are missing links or are not backward compatible. e.g. the dblink_ora doesn't work for version12

## Where did you see the problem?

If you go to https://www.enterprisedb.com/docs/epas/latest/epas_compat_ora_dev_guide/06_dblink_ora/ (for instance) and pick v12 from the dropdown on the left nav, the page refreshes to: https://www.enterprisedb.com/docs/epas/12/

## Expected behavior
I was hoping to get the version 12 copy of the dblink_ora topic.

## Additional notes
This issue originated from an anonymous user feedback comment.

**Comment by drothery-edb** [comment] 2022-12-29 18:19
Duplicate of #1969

**Closed by drothery-edb** 2022-12-29 18:19 UTC
