### ISSUE TITLE
Problems with interactive installer instructions for PostgreSQL

### ISSUE THREAD

**Issue by drothery-edb** [EnterpriseDB/docs#3490] opened 2022-12-29 19:40 UTC
A number of related issues have been submitted related to the interactive installers:

- https://github.com/EnterpriseDB/docs/issues/2942
- https://github.com/EnterpriseDB/docs/issues/2177 - Closed
- https://github.com/EnterpriseDB/docs/issues/2053 - Closed
- https://github.com/EnterpriseDB/docs/issues/1449 - Closed
- https://github.com/EnterpriseDB/docs/issues/3460 - Closed

There are also some Jira tickets:

- https://enterprisedb.atlassian.net/browse/DF-261 -Closed
- https://enterprisedb.atlassian.net/browse/DF-48 - Closed

And, here is a related Language Pack issue: 

- https://github.com/EnterpriseDB/docs/issues/799

Notes on overall project are here: [PostgreSQL install doc](https://docs.google.com/document/d/1fLJ51EAy3zrE-396DFlyiwHvK4U6yxH0N-0VizXwsSw/edit)
Details about individual issues and tickets are here: [GitHub issues and DF tickets related to installing PostgreSQL](https://docs.google.com/spreadsheets/d/10JdEp5ZD1ZIR0yAEZvFNaZOTCwEYOXZGvU3SCEwM-FU/edit#gid=0)

**Comment by dwicinas** [comment] 2023-01-10 16:50
Some notes on these issues:
#2942 - Unable to determine if there could be a problem with Run as Administrator, unless the user was running 32-bit Windows. Should I just close this issue?
#2177 - Seems to be the same issue as #1449. Is there a way to link this issue to 1449?
#2053 - One way to address this issue is to include a statement saying that uninstalling PostgreSQL does not also uninstall modules installed using Stack Builder. The issue is raised for Mac, but does it only apply to Mac or both Mac and Windows? A better solution might be to provide instructions for both Windows and Mac describing how to remove other modules installed using Stack Builder. Can Nidhi provide a procedure for uninstalling on both platforms?
#1449 - Add a note in the Requirements page saying the username can only contain ASCII characters.
#3460 - The procedure for using the Windows wizard is inconsistent because it calls out all the other pages in the wizard but not the page for Port. The procedure could be revised simply. The procedure could also be made more overtly procedural by inserting step numbers. It's already pretty procedural but it currently lacks those step numbers. While considering this topic, we could consider eliminating the screen shots. They are nice but don't add a great deal of value. The same issues apply to "Using Stack Builder." We could drop the screen shots. And we could add step numbers.
DF-261 - Does a list of command line parameters for Postgres exist? And if so, is there a reasonable way to determine how to use them?
DF-48 - Does it make sense to present installation instructions for PostgreSQL like we do for other EDB products? If we did that, we would have to set up a template structure for PostgreSQL, which seems doable, though not a small job. Do we benefit from that effort? We mostly have the information needed to start reorganizing the PostgreSQL install information and setting up templates. However, we seem to lack instructions for installing on Mac. I'll need to do a more thorough evaluation for this issue.
#799 - Possibly include a stub topic introducing Language Pack and linking to the Language Pack section in EPAS.

**Comment by drothery-edb** [comment] 2023-01-31 12:10
JIRA ticket for character set issues: https://enterprisedb.atlassian.net/browse/DBP-191

**Comment by gvasquezvargas** [comment] 2024-10-04 14:17
Closing this as https://github.com/EnterpriseDB/docs/pull/6024 with latest updates has gone live.

**Closed by gvasquezvargas** 2024-10-04 14:17 UTC
