### ISSUE TITLE
Regarding Docs build instructions /community/contributing/repo.mdx

### ISSUE THREAD

**Issue by trgegs** [EnterpriseDB/docs#2790] opened 2022-06-14 08:13 UTC
## Summary

I'm trying to follow the instructions to use the docs repository on my EDB work laptop (MacOS) but run into the following issues:
- The instructions are unclear in that 'Installing Node.js' from its website is mentioned, but also 'brew install node'
- When I follow the instructions, even though I have a valid login and cached credentials for the node registry, I get a login error trying to do 'node install' in the .../docs directory. I've made sure the local token is correct and up to date.

## Where did you see the problem?

On the instruction page for working with the docs git repository

## Expected behavior

- The instructions have to be reviewed and brought into line with best practices by pointing to the instructions for installing Node.js and not have people install with brew on MacOS. (Preferably using something like 'nvm', according to the NPM website.)
- Login needs to work

## Screenshots
![image](https://user-images.githubusercontent.com/20049056/173527606-2b9515c3-f229-4e64-94fa-310b9d8d2fc2.png)
## Browser / Platform

MacOS on Intel, NodeJS lts,

## Additional notes

Anything else you'd like to add that might help us to fix the problem

**Comment by djw-m** [comment] 2024-01-24 15:53
We came back to this after being unable to reproduce the error in installations. We waited until we had a new clean user to run through the the entire installation process and as of currently no errors are being experienced by new users. We are closing this ticket for now, but will look at clarifying the node installation instructions (though again, they proved no hurdle in recent tests)

Dj

**Closed by djw-m** 2024-01-24 15:53 UTC
